# Makefile for rooting homework
# @author Fady Ghanim
# @revision $Id$
#
#===========================================================================
#
# STUDENTID= your account name.
#

include /opt/xmt/class/make/rooting.mk
